import pandas as pd
import logging
from fastapi import FastAPI, HTTPException, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from backend.data_engine import initialize_database
from backend.query_engine import generate_query
from backend.data_engine import run_query
from backend.insight_engine import generate_insight
from backend.chart_engine import select_chart
from backend.context_manager import store_query, get_context
from backend.response_formatter import format_response
from backend.upload_handler import upload_dataset, detect_schema, store_dataset

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="AI Marketing Analytics API")
@app.on_event("startup")
def startup_event():
    initialize_database()

# Enable CORS for frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust this in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class QueryRequest(BaseModel):
    question: str

class QueryResponse(BaseModel):
    chart: str
    title: str
    data: list
    insight: str

@app.post("/upload")
async def upload_file(file: UploadFile = File(...)):
    """
    Endpoint to upload a CSV dataset, detect its schema, and store it for analytics.
    """
    logger.info(f"Received file upload: {file.filename}")
    if not file.filename.endswith('.csv'):
        raise HTTPException(status_code=400, detail="Only CSV files are supported.")
        
    try:
        # Pass the SpooledTemporaryFile to pandas
        try:
            # First try UTF-8
            contents = await file.read()
            df = upload_dataset(contents)
        except UnicodeDecodeError:
            # Reset file pointer and retry with latin1
            file.seek(0)
            contents = await file.read()
            df = upload_dataset(contents, encoding="latin1")
        
        # Detect schema
        schema_cols = detect_schema(df)
        
        # Store to SQLite
        store_dataset(df)
        
        return {
            "message": "Dataset uploaded successfully",
            "columns": schema_cols,
            "rows": len(df)
        }
    except Exception as e:
        logger.error(f"Dataset upload failed: {e}")
        raise HTTPException(status_code=500, detail=f"Upload failed: {str(e)}")

@app.post("/query", response_model=QueryResponse)
def process_query(request: QueryRequest):
    """
    Endpoint to process a natural language question and return structured analytics.
    """
    question = request.question
    logger.info(f"Received question: {question}")
    
    # Retrieve previous conversation context
    context = get_context()
    
    # 1. Generate query using LLM
    try:
        # Pass the context to query generation
        query_info = generate_query(question, context)
        
        # Assume query_info is a dictionary containing sql, chart, title
        sql = query_info.get("sql")
        chart = query_info.get("chart", "bar")
        title = query_info.get("title", "Analysis Result")
        
        if not sql:
            raise ValueError("No SQL generated by query engine.")
            
        logger.info(f"Generated SQL: {sql}")
        
    except Exception as e:
        logger.error(f"Query generation failed: {e}")
        raise HTTPException(
            status_code=500, 
            detail=f"Query generation failed: {str(e)}"
        )
        
    # 2. Execute SQL
    try:
        df = run_query(sql)
        # Convert pandas DataFrame to list of dictionaries for JSON payload
        data = df.to_dict(orient="records")
        logger.info(f"Query executed successfully, returned {len(data)} rows.")
        
        # Override chart type using the intelligent chart engine
        chart = select_chart(question, df)
        logger.info(f"Selected chart type: {chart}")
        
    except Exception as e:
        logger.error(f"SQL execution failed: {e}")
        raise HTTPException(
            status_code=500, 
            detail=f"SQL execution failed: {str(e)}"
        )
        
    # 3. Generate insight from the dataframe
    try:
        insight = generate_insight(question, df)
        logger.info("Insight generated successfully.")
        
    except Exception as e:
        logger.error(f"Insight generation failed: {e}")
        raise HTTPException(
            status_code=500, 
            detail=f"Insight generation failed: {str(e)}"
        )
        
    # 4. Return the constructed response
    # Only store query if the entire process succeeds
    store_query(question)
    
    formatted_payload = format_response(df, chart, title, insight)
    
    return QueryResponse(**formatted_payload)

if __name__ == "__main__":
    import uvicorn
    # You can run this directly with `python api.py`
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
