import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from query_engine import generate_query
from data_engine import run_query
from insight_engine import generate_insight
from context_manager import store_query, get_context

# Setup logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="AI Marketing Analytics API")

# Enable CORS for frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Adjust this in production
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class QueryRequest(BaseModel):
    question: str

class QueryResponse(BaseModel):
    chart: str
    title: str
    data: list
    insight: str

@app.post("/query", response_model=QueryResponse)
def process_query(request: QueryRequest):
    """
    Endpoint to process a natural language question and return structured analytics.
    """
    question = request.question
    logger.info(f"Received question: {question}")
    
    # Retrieve previous conversation context
    context = get_context()
    
    # 1. Generate query using LLM
    try:
        # Pass the context to query generation
        query_info = generate_query(question, context)
        
        # Assume query_info is a dictionary containing sql, chart, title
        sql = query_info.get("sql")
        chart = query_info.get("chart", "bar")
        title = query_info.get("title", "Analysis Result")
        
        if not sql:
            raise ValueError("No SQL generated by query engine.")
            
        logger.info(f"Generated SQL: {sql}")
        
    except Exception as e:
        logger.error(f"Query generation failed: {e}")
        raise HTTPException(
            status_code=500, 
            detail=f"Query generation failed: {str(e)}"
        )
        
    # 2. Execute SQL
    try:
        df = run_query(sql)
        # Convert pandas DataFrame to list of dictionaries for JSON payload
        data = df.to_dict(orient="records")
        logger.info(f"Query executed successfully, returned {len(data)} rows.")
        
    except Exception as e:
        logger.error(f"SQL execution failed: {e}")
        raise HTTPException(
            status_code=500, 
            detail=f"SQL execution failed: {str(e)}"
        )
        
    # 3. Generate insight from the dataframe
    try:
        insight = generate_insight(question, df)
        logger.info("Insight generated successfully.")
        
    except Exception as e:
        logger.error(f"Insight generation failed: {e}")
        raise HTTPException(
            status_code=500, 
            detail=f"Insight generation failed: {str(e)}"
        )
        
    # 4. Return the constructed response
    # Only store query if the entire process succeeds
    store_query(question)
    
    return QueryResponse(
        chart=chart,
        title=title,
        data=data,
        insight=insight
    )

if __name__ == "__main__":
    import uvicorn
    # You can run this directly with `python api.py`
    uvicorn.run("api:app", host="0.0.0.0", port=8000, reload=True)
