import re

def validate_sql(sql_query: str) -> str:
    """
    Validates an AI-generated SQL query to ensure it is safe to execute.
    
    Args:
        sql_query (str): The SQL query string generated by the AI model.
        
    Returns:
        str: The validated and potentially modified safe SQL query.
        
    Raises:
        ValueError: If the query violates any security rules.
    """
    if not sql_query or not isinstance(sql_query, str):
        raise ValueError("Invalid SQL query.")

    clean_query = sql_query.strip().strip(";")
    # Ensure there's no trailing whitespace after removing semicolon
    clean_query = clean_query.strip()
    query_upper = clean_query.upper()

    # Rule 1: Allow only SELECT queries
    if not query_upper.startswith("SELECT"):
        raise ValueError("Safety violation: Only SELECT queries are allowed.")

    # Rule 2: Block unsafe keywords
    forbidden_words = ["DROP", "DELETE", "UPDATE", "INSERT", "ALTER", "CREATE"]
    for word in forbidden_words:
        # Check if the restricted keyword is used as a full word
        if re.search(fr'\b{word}\b', query_upper):
            raise ValueError(f"Safety violation: Query contains forbidden keyword '{word}'.")

    # Rule 3: Ensure the query references ONLY marketing_data
    if "MARKETING_DATA" not in query_upper:
        raise ValueError("Safety violation: Query must reference the 'marketing_data' table.")
         
    # Extract all tables mentioned after FROM or JOIN, ignoring potential quotes
    tables = re.findall(r'\b(?:FROM|JOIN)\s+[\'"]?([A-Z0-9_]+)[\'"]?', query_upper)
    for table in tables:
        if table != "MARKETING_DATA":
            raise ValueError(f"Safety violation: Query accesses unauthorized table '{table}'. Only 'marketing_data' is allowed.")

    # Rule 4: Limit query results to 100 rows maximum
    limit_match = re.search(r'\bLIMIT\s+(\d+)', query_upper)
    
    if limit_match:
        limit_val = int(limit_match.group(1))
        if limit_val > 100:
            raise ValueError("Safety violation: LIMIT exceeds maximum allowed rows (100).")
    else:
        # Append LIMIT 100 if not present
        clean_query += " LIMIT 100"

    return clean_query
